version: "3"
services:
  client:
    image: "skymnok/multi-client"
    hostname: client
    deploy:
      resources:
        limits:
          memory: 128M
  server:
    image: "skymnok/multi-server"
    deploy:
      resources:
        limits:
          memory: 128M
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "skymnok/multi-worker"
    deploy:
      resources:
        limits:
          memory: 128M
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "skymnok/multi-nginx"
    deploy:
      resources:
        limits:
          memory: 128M
    hostname: nginx
    ports:
      - "3050:80"